source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# bundle open calais gem
gem 'open_calais'
# bundle sentimental gem
gem 'sentimental'
# bundle alchemy api
gem 'alchemy-api-rb', require: 'alchemy_api'
# bundle indico gem
gem 'indico', '~> 0.5.3'
# bundle highscore api
gem 'highscore', '~> 1.2'
# bundle mandrill api
gem 'mandrill-api'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
# Use act as taggabel on
gem 'acts-as-taggable-on'
# Use search bar auto completing
gem 'rails4-autocomplete'
# Use html sanitizer
gem 'rails-html-sanitizer'
# Use Unicorn as the app server
# gem 'unicorn'
gem 'tzinfo-data'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# Use kaminari as paginator solution
gem 'kaminari'
# Use ransack as string matching solution
gem 'ransack'

gem 'excon'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
