# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36273cb6390a0e8290ece6429d82759caeb33606dca9f5ce74d4cd740ca1aca6c34ca69d187c576ecfe6b949c22b3cfdc3635a2ebd93c516c55240dbdaa0fa2

test:
  secret_key_base: 28b04e6c0840f51e1d8ad38cbdc6e89aa26f3b7cb6b251747bad822535c120044a951bdf65c71bafd06bbde661cb75953f9595768b79f8488cd2cab130ed6fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
